version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lansight
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./lansight-backend/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build:
      context: ./lansight-backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lansight
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  db_data:
